version: '3.8'
services:
  frontend:
    container_name: frontend
    image: node:10.20-alpine
    build: ./spring-petclinic-angular
    ports:
      - published: 4200
        target: 4200

  nginx:
    container_name: nginx
    image: nginx:latest
    build: ./NGINX
    ports:
      - published: 80
        target: 80
    volumes:
      - type: bind
        source: ./NGINX/nginx.conf
        target: /etc/nginx/nginx.conf

  backend:
    container_name: backend
    image: springcommunity/spring-petclinic-rest
    build: ./spring-petclinic-rest
    ports:
      - published: 9966
        target: 9966